# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160731_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
