# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='upload', verbose_name='文件'),
        ),
    ]
